#!/bin/bash

Main() {
    local conf=/etc/starlight-rankmirrors.conf
    source $conf || return

    local timeout="$EOS_AUTORANK_TIMEOUT"
    [ -n "$timeout" ] || timeout=30

    /usr/bin/starlight-rankmirrors --timeout $timeout --hook-rank >/dev/null || true
    return 0
}

Main "$@"
